name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'techdebt'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'chore'
    branch:
      - '/(chore|debt|techdebt)\/.+/'
  - label: 'techdebt'
    branch:
      - '/(chore|debt|techdebt)\/.+/'
  - label: 'bug'
    branch:
      - '/(fix|bug)\/.+/'
  - label: 'patch'
    branch:
      - '/(fix|bug)\/.+/'
  - label: 'enhancement'
    branch:
      - '/(feature|feat)\/.+/'
  - label: 'minor'
    branch:
      - '/(feature|feat)\/.+/'
  - label: 'major'
    branch:
      - '/epic\/.+/'
template: |
  ## What's New

  $CHANGES