name: Save Release Notes

on:
  release:
    types: [created, edited]

jobs:
  save-release-notes:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Save Release Notes
        id: savereleasenotes
        uses: actions/github-script@v7
        with:
          script: |
            const releaseNotes = `export const ReleastNotesMD = ${"`"}${context.payload.release.body}${"`"};` + "\n\n" + `export const ReleaseVersion = "${context.payload.release.tag_name}";` + "\n\n" + `export const ReleaseTime = ${new Date().getTime()};`;
            const fileName = 'frontend/src/components/ReleaseNotes/ReleastNotesMD.js';
            let sha;

            try {
              const { data } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: fileName
              });
              sha = data.sha;
            } catch (e) {}

            await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: fileName,
              message: 'Update release notes',
              content: Buffer.from(releaseNotes).toString('base64'),
              sha: sha || context.repo.sha
            });
